<a href="https://colab.research.google.com/github/jaemin799/test1/blob/main/load_digits.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [5]:
load_digits

<function sklearn.datasets._base.load_digits(*, n_class=10, return_X_y=False, as_frame=False)>

In [6]:
type(load_digits)

function

In [7]:
digits = load_digits()
print(dir(digits)) #EXPLORATION[1-3]

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']


In [8]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [9]:
digits.data.shape

(1797, 64)

In [10]:
digits.feature_names

['pixel_0_0',
 'pixel_0_1',
 'pixel_0_2',
 'pixel_0_3',
 'pixel_0_4',
 'pixel_0_5',
 'pixel_0_6',
 'pixel_0_7',
 'pixel_1_0',
 'pixel_1_1',
 'pixel_1_2',
 'pixel_1_3',
 'pixel_1_4',
 'pixel_1_5',
 'pixel_1_6',
 'pixel_1_7',
 'pixel_2_0',
 'pixel_2_1',
 'pixel_2_2',
 'pixel_2_3',
 'pixel_2_4',
 'pixel_2_5',
 'pixel_2_6',
 'pixel_2_7',
 'pixel_3_0',
 'pixel_3_1',
 'pixel_3_2',
 'pixel_3_3',
 'pixel_3_4',
 'pixel_3_5',
 'pixel_3_6',
 'pixel_3_7',
 'pixel_4_0',
 'pixel_4_1',
 'pixel_4_2',
 'pixel_4_3',
 'pixel_4_4',
 'pixel_4_5',
 'pixel_4_6',
 'pixel_4_7',
 'pixel_5_0',
 'pixel_5_1',
 'pixel_5_2',
 'pixel_5_3',
 'pixel_5_4',
 'pixel_5_5',
 'pixel_5_6',
 'pixel_5_7',
 'pixel_6_0',
 'pixel_6_1',
 'pixel_6_2',
 'pixel_6_3',
 'pixel_6_4',
 'pixel_6_5',
 'pixel_6_6',
 'pixel_6_7',
 'pixel_7_0',
 'pixel_7_1',
 'pixel_7_2',
 'pixel_7_3',
 'pixel_7_4',
 'pixel_7_5',
 'pixel_7_6',
 'pixel_7_7']

In [19]:
len(digits.feature_names)

64

In [12]:
digits.keys()

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

In [25]:
#EXPLORATION[1-8]
digits_data = digits.data

In [14]:
#EXPLORATION[1-4]
import pandas as pd

In [26]:
type(digits_data)

numpy.ndarray

In [27]:
digits_data.shape

(1797, 64)

In [28]:
print(digits.target)

[0 1 2 ... 8 9 8]


In [29]:
digits.target.shape

(1797,)

In [31]:
print(digits.target_names)

[0 1 2 3 4 5 6 7 8 9]


In [32]:
digits_label = digits.target
print(digits_label.shape)

(1797,)


In [34]:
x_train, x_test, y_train, y_test = train_test_split(digits_data, digits_label, test_size=0.2)

In [35]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(1437, 64) (1437,)
(360, 64) (360,)


In [36]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(x_train, y_train)

DecisionTreeClassifier()

In [40]:
y_pred = dt.predict(x_test)
print(y_pred)

[7 5 7 3 2 1 4 5 4 2 7 2 7 2 5 2 4 0 7 0 1 7 2 1 7 7 8 8 8 0 6 5 1 2 2 3 4
 2 5 7 5 0 5 7 8 0 8 8 0 1 4 4 0 3 7 2 9 9 8 6 0 6 7 3 0 8 6 7 7 1 0 3 0 1
 1 1 2 4 6 9 6 8 1 8 9 8 2 3 3 7 3 9 7 4 0 5 3 2 3 3 7 6 3 0 9 4 1 3 7 4 4
 5 1 6 9 7 3 7 0 6 3 8 0 8 2 3 8 7 4 1 3 8 0 7 9 6 8 0 4 1 0 1 7 4 3 6 0 1
 6 8 5 4 1 1 7 0 0 8 9 3 9 8 5 4 3 2 3 2 7 2 6 1 4 3 1 0 2 2 7 6 0 4 5 1 2
 4 4 3 0 1 7 5 7 5 3 1 3 5 5 7 3 9 4 6 1 7 4 7 7 5 7 0 4 7 2 7 6 5 3 6 8 1
 6 9 2 1 5 2 4 3 1 8 7 8 2 7 7 8 6 4 3 6 6 8 4 5 7 3 2 5 7 2 0 5 6 4 6 4 3
 9 5 1 5 2 4 6 1 4 9 6 9 9 0 8 5 5 3 3 5 5 9 2 4 6 9 3 4 4 6 2 9 6 1 0 9 3
 1 8 9 8 6 7 4 3 2 3 1 2 5 3 4 5 3 0 9 2 2 6 6 0 4 4 9 6 9 5 9 6 7 5 1 9 8
 5 2 1 0 0 2 9 3 9 6 6 7 6 5 9 5 7 3 2 7 1 5 6 8 5 8 7]


In [41]:
print(y_test)

[8 9 7 3 2 1 4 5 4 2 7 2 7 2 5 2 4 0 7 0 1 9 2 1 7 7 8 8 2 0 6 5 1 8 2 3 4
 2 5 7 5 0 5 7 9 0 8 8 0 1 4 4 0 3 7 2 9 9 8 6 0 6 7 3 0 8 6 7 3 4 0 3 0 1
 8 1 2 2 6 9 6 8 1 0 9 1 2 3 3 7 3 9 7 4 0 5 3 2 8 3 7 6 3 0 9 4 1 3 9 4 4
 5 1 6 9 7 3 7 0 6 3 8 0 8 2 3 8 7 4 1 3 8 0 7 9 6 0 0 0 1 0 1 7 4 3 6 0 1
 6 4 5 4 1 1 7 6 0 8 9 8 9 8 5 4 9 2 3 2 7 2 6 1 4 3 1 0 2 2 7 6 0 2 5 1 2
 4 4 3 0 1 7 8 7 5 3 1 3 5 5 7 8 9 4 6 1 7 4 7 7 8 7 0 4 7 2 7 6 5 5 6 1 1
 6 9 2 1 5 2 4 3 1 8 7 8 2 7 7 1 6 4 3 2 1 8 4 7 7 8 2 5 7 2 0 5 6 4 4 4 3
 9 5 1 5 2 4 6 1 4 9 6 3 9 0 8 5 5 3 3 5 2 9 2 4 6 9 3 0 6 6 1 9 6 1 0 8 3
 1 8 9 9 6 7 6 8 2 8 1 2 5 8 4 5 3 0 9 2 2 2 5 6 4 4 9 5 9 5 9 6 7 5 1 9 8
 5 2 1 0 0 2 9 3 8 6 5 7 6 5 9 5 7 3 2 7 1 5 6 8 5 8 7]


In [42]:
#EXPLORATION[1-6]
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
accuracy

0.8638888888888889

In [43]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.88      0.91        34
           1       0.94      0.87      0.90        38
           2       0.94      0.85      0.89        40
           3       0.78      0.94      0.85        34
           4       0.84      0.91      0.87        34
           5       0.86      0.89      0.88        36
           6       0.81      0.88      0.85        34
           7       0.91      0.98      0.94        43
           8       0.70      0.60      0.65        35
           9       0.90      0.81      0.85        32

    accuracy                           0.86       360
   macro avg       0.86      0.86      0.86       360
weighted avg       0.87      0.86      0.86       360



In [ ]:
data_frame = pd.DataFrame(data = )