<a href="https://colab.research.google.com/github/jaemin799/test1/blob/main/load_digits.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [ ]:
load_digits

<function sklearn.datasets._base.load_digits(*, n_class=10, return_X_y=False, as_frame=False)>

In [ ]:
type(load_digits)

function

In [ ]:
digits = load_digits()
print(dir(digits)) #EXPLORATION[1-3]

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']


In [ ]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [ ]:
digits.data.shape

(1797, 64)

In [ ]:
digits.feature_names

['pixel_0_0',
 'pixel_0_1',
 'pixel_0_2',
 'pixel_0_3',
 'pixel_0_4',
 'pixel_0_5',
 'pixel_0_6',
 'pixel_0_7',
 'pixel_1_0',
 'pixel_1_1',
 'pixel_1_2',
 'pixel_1_3',
 'pixel_1_4',
 'pixel_1_5',
 'pixel_1_6',
 'pixel_1_7',
 'pixel_2_0',
 'pixel_2_1',
 'pixel_2_2',
 'pixel_2_3',
 'pixel_2_4',
 'pixel_2_5',
 'pixel_2_6',
 'pixel_2_7',
 'pixel_3_0',
 'pixel_3_1',
 'pixel_3_2',
 'pixel_3_3',
 'pixel_3_4',
 'pixel_3_5',
 'pixel_3_6',
 'pixel_3_7',
 'pixel_4_0',
 'pixel_4_1',
 'pixel_4_2',
 'pixel_4_3',
 'pixel_4_4',
 'pixel_4_5',
 'pixel_4_6',
 'pixel_4_7',
 'pixel_5_0',
 'pixel_5_1',
 'pixel_5_2',
 'pixel_5_3',
 'pixel_5_4',
 'pixel_5_5',
 'pixel_5_6',
 'pixel_5_7',
 'pixel_6_0',
 'pixel_6_1',
 'pixel_6_2',
 'pixel_6_3',
 'pixel_6_4',
 'pixel_6_5',
 'pixel_6_6',
 'pixel_6_7',
 'pixel_7_0',
 'pixel_7_1',
 'pixel_7_2',
 'pixel_7_3',
 'pixel_7_4',
 'pixel_7_5',
 'pixel_7_6',
 'pixel_7_7']

In [ ]:
len(digits.feature_names)

64

In [ ]:
digits.keys()

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

In [ ]:
#EXPLORATION[1-8]
digits_data = digits.data

In [ ]:
#EXPLORATION[1-4]
import pandas as pd

In [ ]:
type(digits_data)

numpy.ndarray

In [ ]:
digits_data.shape

(1797, 64)

In [ ]:
print(digits.target)

[0 1 2 ... 8 9 8]


In [ ]:
digits.target.shape

(1797,)

In [ ]:
print(digits.target_names)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
digits_label = digits.target
print(digits_label.shape)

(1797,)


In [ ]:
x_train, x_test, y_train, y_test = train_test_split(digits_data, digits_label, test_size=0.2)

In [ ]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(1437, 64) (1437,)
(360, 64) (360,)


In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(x_train, y_train)

DecisionTreeClassifier()

In [ ]:
y_pred = dt.predict(x_test)
print(y_pred)

[8 9 8 6 6 3 2 4 8 5 5 5 8 3 7 2 4 3 9 9 8 3 1 7 6 9 2 5 0 1 9 3 0 5 7 7 1
 2 1 4 4 8 7 7 3 5 8 5 7 5 5 6 8 2 3 9 0 8 1 8 6 4 9 6 4 2 1 9 7 7 2 6 1 3
 0 7 2 4 0 1 0 6 8 7 4 1 4 1 4 7 1 2 1 9 2 7 5 5 5 6 6 2 5 2 2 0 2 8 9 3 0
 6 9 6 1 1 4 6 1 8 9 6 1 8 0 8 1 0 8 4 4 0 1 1 7 5 6 9 6 6 5 4 1 5 9 8 5 6
 2 0 7 5 2 0 3 7 1 5 7 8 9 4 8 5 1 2 2 0 7 2 8 1 1 2 0 6 8 6 8 7 3 5 3 2 5
 5 3 9 5 8 4 1 8 6 9 0 0 3 7 5 7 4 3 7 0 1 6 9 3 4 0 0 3 3 2 2 9 4 3 0 3 8
 1 8 1 3 3 4 3 7 5 1 2 3 0 1 4 7 9 7 8 2 6 9 7 4 2 2 2 3 9 6 4 9 8 6 8 1 1
 7 6 7 6 7 0 1 9 1 9 0 7 1 4 0 9 9 1 8 9 1 8 3 8 6 5 2 4 6 2 3 2 0 1 4 5 5
 3 8 7 5 3 0 7 4 5 7 5 5 3 3 8 8 1 7 0 1 9 6 6 4 9 3 6 7 8 5 3 4 1 4 9 3 8
 2 0 1 3 4 5 3 0 4 6 5 0 0 3 8 0 9 0 2 7 7 1 3 6 6 5 5]


In [ ]:
print(y_test)

[9 9 8 6 6 3 2 4 8 5 5 3 8 3 7 3 4 3 9 9 8 3 8 7 6 9 2 5 0 1 7 3 0 4 7 7 7
 2 8 4 4 8 7 7 3 5 8 5 7 5 5 6 8 2 3 9 0 5 1 8 6 4 4 6 4 2 1 7 7 7 1 6 1 2
 0 7 2 4 0 2 0 6 8 7 4 2 4 1 4 7 5 2 1 9 2 7 5 5 5 4 6 2 3 2 2 0 2 8 9 3 0
 6 9 6 9 1 2 6 1 8 9 4 9 8 0 2 1 0 8 0 9 0 1 1 7 5 6 7 6 6 5 7 1 5 9 8 5 6
 2 0 7 0 2 0 3 7 3 2 7 8 9 4 8 5 1 2 2 0 7 2 8 1 1 2 0 6 8 6 8 7 3 5 3 3 5
 5 3 9 5 8 4 1 8 6 5 0 0 3 8 5 9 4 3 7 0 1 6 9 3 4 0 0 3 3 2 2 9 4 3 0 2 8
 1 8 9 2 3 4 1 7 5 8 2 3 0 1 4 7 9 7 8 2 6 4 3 4 2 2 2 3 9 6 4 3 8 6 8 8 1
 7 0 7 6 8 0 1 9 4 9 0 7 1 4 0 9 6 1 8 1 1 8 3 8 6 5 2 4 6 2 3 2 0 1 4 5 5
 3 8 9 5 3 0 7 7 5 7 5 5 3 3 8 8 9 7 0 6 4 6 6 4 3 3 6 1 8 5 3 4 1 4 9 9 8
 2 0 1 3 3 5 3 0 4 6 5 0 0 3 9 0 3 0 2 7 7 1 3 6 6 5 5]


In [ ]:
#EXPLORATION[1-6]
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
accuracy

0.8361111111111111

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.92      0.96        37
           1       0.65      0.88      0.75        32
           2       0.91      0.79      0.85        38
           3       0.87      0.77      0.81        43
           4       0.81      0.79      0.80        33
           5       0.87      0.92      0.89        36
           6       0.91      0.94      0.93        34
           7       0.84      0.84      0.84        37
           8       0.89      0.85      0.87        40
           9       0.62      0.67      0.65        30

    accuracy                           0.84       360
   macro avg       0.84      0.84      0.83       360
weighted avg       0.85      0.84      0.84       360



In [ ]:
data_frame = pd.DataFrame(data = digits_data, columns=digits.feature_names)

In [ ]:
data_frame.shape

(1797, 64)

In [ ]:
data_frame['label'] = (digits.target)
data_frame.shape

(1797, 65)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression

In [ ]:
rf = RandomForestClassifier(random_state = 5)
rf.fit(x_train, y_train)

RandomForestClassifier(random_state=5)

In [ ]:
y_pred = rf.predict(x_test)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9722222222222222

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97        37
           1       0.97      1.00      0.98        32
           2       1.00      0.95      0.97        38
           3       0.98      0.98      0.98        43
           4       0.97      1.00      0.99        33
           5       0.92      1.00      0.96        36
           6       1.00      0.94      0.97        34
           7       0.97      1.00      0.99        37
           8       0.97      0.95      0.96        40
           9       0.97      0.93      0.95        30

    accuracy                           0.97       360
   macro avg       0.97      0.97      0.97       360
weighted avg       0.97      0.97      0.97       360



In [ ]:
svm = svm.SVC(random_state = 5)
svm.fit(x_train, y_train)

SVC(random_state=5)

In [ ]:
y_pred = svm.predict(x_test)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9916666666666667

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       0.97      1.00      0.98        32
           2       1.00      1.00      1.00        38
           3       1.00      1.00      1.00        43
           4       1.00      1.00      1.00        33
           5       0.95      1.00      0.97        36
           6       1.00      1.00      1.00        34
           7       1.00      1.00      1.00        37
           8       1.00      0.97      0.99        40
           9       1.00      0.93      0.97        30

    accuracy                           0.99       360
   macro avg       0.99      0.99      0.99       360
weighted avg       0.99      0.99      0.99       360



In [ ]:
sgd = SGDClassifier(random_state = 5)
sgd.fit(x_train, y_train)

SGDClassifier(random_state=5)

In [ ]:
y_pred = sgd.predict(x_test)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9416666666666667

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.97      0.99        37
           1       0.76      1.00      0.86        32
           2       1.00      1.00      1.00        38
           3       1.00      0.95      0.98        43
           4       0.91      0.94      0.93        33
           5       0.95      1.00      0.97        36
           6       0.97      0.97      0.97        34
           7       1.00      0.95      0.97        37
           8       0.97      0.80      0.88        40
           9       0.86      0.83      0.85        30

    accuracy                           0.94       360
   macro avg       0.94      0.94      0.94       360
weighted avg       0.95      0.94      0.94       360



In [ ]:
lr = LogisticRegression(random_state=5)
lr.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(random_state=5)

In [ ]:
y_pred = lr.predict(x_test)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9722222222222222

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       0.91      0.97      0.94        32
           2       1.00      1.00      1.00        38
           3       0.98      0.98      0.98        43
           4       0.94      0.97      0.96        33
           5       0.97      0.97      0.97        36
           6       1.00      0.97      0.99        34
           7       1.00      0.97      0.99        37
           8       0.97      0.97      0.97        40
           9       0.93      0.90      0.92        30

    accuracy                           0.97       360
   macro avg       0.97      0.97      0.97       360
weighted avg       0.97      0.97      0.97       360



최종적으로 선택한 모델은 정확도가 0.99가 나온 SVM으로 하겠습니다.